FROM node:14
WORKDIR /app
COPY ./user/package*.json ./
RUN npm i -g install
COPY ./user .
RUN bootstrap
RUN npm i
RUN npm run common:prepare
RUN npm run build
EXPOSE 3000
CMD [ "npm", "run", "serve" ]
