version: "3"

services:
  admin_service_1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - admin-network

  admin_service_2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - admin-network
      
  admin_service_3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - admin-network

  admin_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - admin-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  admin-network:
