version: "3"

services:
  user_service_1:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - user-network

  user_service_2:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - user-network
      
  user_service_3:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - user-network

  user_nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - user-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  user-network:
